[project]
profile = rust

[rust]
image = rust:latest

[alias:build]
desc = Compile in debug mode.
cmd = rustup default nightly && cargo build

[alias:run]
desc = Compile in debug mode.
cmd = rustup default nightly && cargo run

[alias:ex]
desc = Run dialog example.
cmd = cargo run --example
interactive = true

# ======================================================================================= #
# Claude Environment
# ======================================================================================= #
[claude]
image = rust:latest
setup = apt-get update && apt-get install -y npm && curl -fsSL https://claude.ai/install.sh | bash && curl -fsSL https://raw.githubusercontent.com/JuliusBrussee/caveman/main/install.sh | bash

[alias:run]
desc = Run claude.
cmd = /root/.local/bin/claude
interactive = true
