[project]
profile = "rust"

[rust]
image = "rust:latest"
setup = "rustup component add --toolchain stable-x86_64-unknown-linux-gnu clippy rustfmt"

[rust.fmt]
desc = "Apply format."
cmd = "cargo fmt"

[rust.clippy]
desc = "Apply clippy."
cmd = "cargo clippy --fix --allow-dirty"

[rust.build]
desc = "Compile in debug mode."
cmd = "cargo build"

[rust.release]
desc = "Compile in release mode."
cmd = "cargo build --release"

[rust.run-demo]
desc = "Run demo."
cmd = "cargo run -- --demo"
interactive = true
hidden = true

[rust.demo]
desc = "Run demo"
pipeline = ["build", "run-demo"]

[rust.build-dialog]
desc = "Build dialog example."
cmd = "cargo build --example dialog"
hidden = true

[rust.run-dialog]
desc = "Run dialog example."
cmd = "cargo run --example dialog"
interactive = true
hidden = true

[rust.dialog]
desc = "Run dialog example"
pipeline = ["build-dialog", "run-dialog"]
